version: '3.8'

services:
  junos-mcp-server:
    build: .
    image: junos-mcp-server:latest
    container_name: junos-mcp-server-http
    ports:
      - "${MCP_SERVER_PORT:-30030}:30030"
    volumes:
      - ${NETWORK_DEVICES_PATH}:/app/network_devices:ro
    environment:
      - MCP_SERVER_HOST=0.0.0.0
      - MCP_SERVER_PORT=30030
      - MCP_TRANSPORT=streamable-http
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DEVICE_CONFIG=/app/network_devices/devices.json
    command: python jmcp.py -f /app/network_devices/devices.json -t streamable-http -H 0.0.0.0 -p 30030
